### ISSUE TITLE
First-class networks

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#143]
- [x] Support networks that can be created at the start of a pipeline and shared between steps
- [x] Add `ports`,  `-p` for publishing ports
- [x] Allow `--name` to be specified via `id`
- [x] Allow specifying `--network` to interact with the host

**Comment by sajayantony** [comment]
```YAML
steps:
- build: -t server:{{.Run.ID}} .
- build: -t testclient -f test/Dockerfile .
- id: app
  cmd: server:{{.Run.ID}}
  ports: 8080:80
  detach: true
- cmd: testclient --url https://app:8080
- push: server:{{.Run.ID}}
```
