### ISSUE TITLE
Support Publishing build artifacts in acb.yaml

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#210]
Currently the task is only able to push containers. The task should also be able to publish multiple artifacts that can be served by the registry as a part of container building. 
The current proposal is to model after this definition

```
steps: 
  - cmd: make something 
     - publish: 
         - a: ./somefile.txt
         - b: ./somefolder
```
