### ISSUE TITLE
Rename step property envs to env

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#254]

**Comment by ehotinger** [comment]
@sajayantony by doing this we will become inconsistent with secrets later on, what is your proposed syntax for this:

```
secrets:
  - akv: "someAKV"
    secretEnv: "someAkvSecretEnv"

steps:
  - id: puller
    cmd: azure/images/docker pull ubuntu
    envs: ["eric=foo", "foo=bar"]
    secretEnvs: ["someAkvSecretEnv"]
```
