### ISSUE TITLE
Support Networking so that containers can talk to each other 

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-builder#255]
This is the sample scenario - 

```YAML
steps:
- build: -t server:{{.Run.ID}} .
- build: -t testclient -f test/Dockerfile .
- id: app
  cmd: server:{{.Run.ID}}
  ports: 8080:80
  detach: true
- cmd: testclient --url https://app:8080
- push: server:{{.Run.ID}}
```
