### ISSUE TITLE
Get error when running several windows container concurrently

### ISSUE THREAD

**Issue by Jinhuafei** [Azure/acr-builder#316]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened?**:
When running the following task, got error from time to time.

**Error Message**
run_4.7.2-windowsservercore-ltsc2016 cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine: The system cannot find the file specified.

**task.yaml**
```yaml
steps:
  - id: run_4.7.2-windowsservercore-1709
    cmd: --entrypoint "ping" {{.Values.registerName}}/{{.Values.repositoryName}}:4.7.2-{{.Values.date}}-windowsservercore-1709 -t www.google.com
    detach: true

  - id: run_4.7.2-windowsservercore-ltsc2016
    cmd: --entrypoint "ping" {{.Values.registerName}}/{{.Values.repositoryName}}:4.7.2-{{.Values.date}}-windowsservercore-ltsc2016 -t www.google.com
    detach: true

  - id: ping_run_4.7.2-windowsservercore-1709
    cmd: --entrypoint "ping" {{.Values.registerName}}/{{.Values.repositoryName}}:3.5-{{.Values.date}}-windowsservercore-1709 run_4.7.2-windowsservercore-1709
    when: ['run_4.7.2-windowsservercore-ltsc2016']

  - id: ping_run_4.7.2-windowsservercore-ltsc2016
    cmd: --entrypoint "ping" {{.Values.registerName}}/{{.Values.repositoryName}}:3.5-{{.Values.date}}-windowsservercore-1709 run_4.7.2-windowsservercore-ltsc2016
    when: ['run_4.7.2-windowsservercore-ltsc2016']

  - id: another_ping_run_4.7.2-windowsservercore-ltsc2016
    cmd: --entrypoint "ping" {{.Values.registerName}}/{{.Values.repositoryName}}:3.5-{{.Values.date}}-windowsservercore-1709 run_4.7.2-windowsservercore-ltsc2016
    when: ['run_4.7.2-windowsservercore-ltsc2016']
```
