### ISSUE TITLE
Ability to pass variable across the steps

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#493]
**What is the problem you're trying to solve**
1) Should be able to set variables/object from a step.
2) Should be able to get variables/object in a step.

Maybe something like this?

```yaml
- id: myImageStep
   cmd: myImage
   taskEnv: [color=red]
- cmd: bash -c 'echo Color is {{.TaskEnv.color}} and \
myImages exit status was {{.Step.myImageStep.exitStatus}}'
```

**Describe the solution you'd like**

**Additional context**
