### ISSUE TITLE
Task unmarshaling fails with aliases

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#511]
**Describe the bug**

**To Reproduce**

Run this task:

```
version: v1.1.0
alias:
  values:
    repo: myrepo
steps:
  - build: -t $Registry/$repo:$ID  -t $Registry/hello-world:$ID -f Dockerfile .
  - push:
    - "$Registry/hello-world:$ID"
```

1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**
