### ISSUE TITLE
Support "mounting" values and secrets through file 

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#550]
**What is the problem you're trying to solve**

Allow passing values and secrets to each step through file

```
volumes:
- name: foo
  values: 
   mysecret1: {{.Secrets.mysecret1}}  

steps:
- cmd: image
  mounts: 
  - name: foo
    mountPath: '/run/foo'
```
