### ISSUE TITLE
Platform linux/arm64 fails for build cache

### ISSUE THREAD

**Issue by shahzzzam** [Azure/acr-builder#571]
**Describe the bug**

```
az acr run -r samashahtest -f - /dev/null
version: v1.0.0
steps:
  - build: -t samashahtest.azurecr.io/acb:arm64  --platform linux/arm64 https://github.com/Azure/acr-builder.git
    cache: "enabled"
```

Fails with the error:

```Error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to load LLB: runtime execution on platform linux/arm64 not supported
Usage:
  /buildx build [OPTIONS] PATH | URL | - [flags]

```
**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**
